apiVersion: v1
kind: Service
metadata:
  name: molecule-service
  labels:
    app: molecule
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: molecule
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
