apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: molecule-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
  labels:
    app: molecule
spec:
  defaultBackend:
    service:
      name: molecule-service
      port:
        number: 8080
