imports:
- path: ../boomi_molecule.jinja

resources:
- name: boomi-gke-quickstart
  type: boomi_molecule.jinja
  properties:
    zone: us-central1-a
    boomiUserEmailID: g.madhukar.yeole@accenture.com
    boomiPassword: 
    boomiAccountID: accentureengineeringmaste-25T6QY
